<div id="howTo">
    <ul class='bulletList'>
        <li onclick="dropDown(this);" class="howToQ">Where am I ?</li><li style='display:block' class="howToA">You are in the PengYou Web "how to" section, the user guide of the PengYou Web application. Hopefully, you will find answers to your questions and solutions to your problems here. Simply click on any link below to get the related explanation. You should take your time to read this section so that you don't waste time getting familiar with the PengYou Web application.</li>
        <li onclick="dropDown(this);" class="howToQ">What is the use for PengYou Web ?</li><li class="howToA">PengYou Web is your PengYou management tool. Using this application, you can access your PengYou system from anywhere as long as you have an Internet connection. You can manage your files, follow up their modification and download them. You may also manage the users, adding new ones and modifying others' access rights. The PengYou Web gives you a secure freedom as a mobile manager.</li>
    <li onclick="dropDown(this);" class="howToQ">Can I access PengYou Web from anywhere ?</li><li class="howToA">PengYou Web is accessible from every computer with an Internet connection. But clearly, for security reasons, your system's administrator may chose to filter the access. He can for instance, allow access to the computers inside your company and to your personal home computer. The PengYou application is fully configurable, you may use it as you wish.</li>
        <li onclick="dropDown(this);" class="howToQ">Does PengYou Web leave any information about me on the computer I use ?</li><li class="howToA">As the PengYou application is meant to be used in companies, we understand the potential confidentiality level of your files. Thus, PengYou Web ensures a complete confidentiality. No cookies are dropped on your computer.</li>
        <li onclick="dropDown(this);" class="howToQ">What can I do with PengYou Web ?</li><li class="howToA">PengYou Web gives you every file management functionality you have on a classic file browser. Here is a short list of the tasks you may achieve:<ul><li>Create directories (<img src='./img/actions/folder_new.png' alt='' title='Create directory'/>)</li><li>Add new files by uploading them (<img src='./img/actions/file_new.png' alt='' title='New file'/>)</li><li>Compress &amp; download documents (<img src='./img/actions/save.png' alt='' title='Compress and download'/>)</li><li>Hold favorites</li><li>Move or Copy documents (<img src='./img/actions/cut.png' alt='' title='Move documents'/>)</li><li>Delete folders and documents (<img src='./img/actions/trash.png' alt='' title='Delete files'/>)</li><li>Search files in your PengYou directories (<img src='./img/actions/find.png' alt='' title='Search documents'/>)</li><li>Consult the version history of your documents</li><li>Rollback to previous versions</li></ul></li>
    <li onclick="dropDown(this);" class="howToQ">How do I browse directories ?</li><li class="howToA">You should browse directories as you do in your usual file explorer: by double clicking the directories. If you wish to go back to a parent directory, you can click any parent directory on the browsing rail and access it. If you wish to refresh the contents of the current file list, please use the refresh button  (<img src='./img/actions/reload.png' alt='' title='Refresh'/>) on your toolbar.</li>
	<li onclick="dropDown(this);" class="howToQ">Why does the "back" button of my browser take me to the page called "home" ?</li><li class="howToA">PengYou web is developped using AJAX technology. This technology allows to create light webpages, modifying the contents without reloading the pages. The problem is that the taken actions are not recognized by web explorers as they consider the page never changes. That is why the click on the "back" button takes you to the previously loaded page. The PengYouWeb interface is designed in order to respond to all your browsing needs, we recommend you to use de PengYou Web interface to surf, and to dismiss your browser buttons.</li>
	<li onclick="dropDown(this);" class="howToQ">What does the "ClipBoard" stand for ?</li><li class="howToA">The Clipboard is your file holder. You can easily load files into the Clipboard by selecting them. Once you have all your desired files in your Clipboard, you can apply action to these such as delete, move, copy, or download. Briefly, if you want to apply an action on a file you should load it in the Clipboard first. This way, you can apply actions to multiple files with one click only, without wasting time. But be careful! The files in your ClipBoard are emptied when you disconnect from PengYou Web.</li>
	<li onclick="dropDown(this);" class="howToQ">What does the "My quick files" stand for ?</li><li class="howToA">This box contains your favorites files. You can put any desired file in this box. This way, you can quickly access to the files you use most of the time. The files in your QuickFiles are kept when you disconnect from PengYou Web.</li>
	<li onclick="dropDown(this);" class="howToQ">How do I apply actions on my files ?</li><li class="howToA">You apply actions to files by selecting them. The selection is called "sticky selection". To select a file, you single click it and see a visual change to dissociate selected files. You may also use the quick select buttons of your toolbar. These buttons allow you to select all the files of a directory, you can also invert your selection. Let's say for example that you want to select all the files in directory but one. To do so quickly, you select the file you don't want, and then invert it's selection. The file you don't want will be unselected and all the others will be selected. PengYou Web allows you to gather files from different directories. This way, you can create instant virtual directories. For instance, if you want to clean your PengYou space, you can cruise the file hierarchy and select all the files you don't need anymore. Once done, all these files can be deleted at the same time with a simple click.</li>
        <li onclick="dropDown(this);" class="howToQ">How can I download files ?</li><li class="howToA">There are two ways to download files using PengYou Web. If you want to quickly download one specific file, you can double click it and launch its download. Otherwise, if you wish to download more than one files (files that are located in different directories), you may select them all to add them to your clipboard, and click the "compress and download" button of your clipboard. PengYou web will then prepare an archive of your selected files, keeping their directory hierarchy, and launch the download. The downloaded archive will be a zip file that you may open using Winzip or Winrar.</li>
        <li onclick="dropDown(this);" class="howToQ">The directory browser is too basic, can't I have access to more information for a given file ?</li><li class="howToA">You may try the different views proposed by PengYou Web. You can either browse the simple view, or chose the detailed view. This one gives a direct visual of the file name, its type, its author, its size and its creation date.</li>
        <li onclick="dropDown(this);" class="howToQ">Why am I disconnected every once in a while from PengYou Web ?</li><li class="howToA">You would not want some one to access your files while you are away from your computer. This is the reason why, when your session is idle for a given amount of time, it is automatically destroyed. You may reconnect using your username and password. PengYou Web gives a secure dimension to your collaboration.</li>
        <li onclick="dropDown(this);" class="howToQ">I can't find the solution to my question here, help me!</li><li class="howToA">Our advise is for you to contact your company's system's administrator for further details. If not possible, you can clearly visit our forum on our website (<a href="http://www.pengyou-project.info">http://www.pengyou-project.info</a>) and ask your question to us directly.</li>
    </ul>
</div>
